### ISSUE TITLE
A Python notebook showing a prototype of French keyboard supporting "inclusive writing"

### ISSUE THREAD

**Issue by Naereen** [Naereen/notebooks#21]
I was discussing with a friend, and realized that I started a few months ago to write, *as much as possible*, my French text messages using an [inclusive writing](https://www.ecriture-inclusive.fr/). For example:

> Tu vas voir tes amis ? → Tu vas voir tes ami-e-s ?

Ideally, I would like my keyboard to suggest me words like this.
But I'm not an Android programmer, and I don't have time to learn this (right now).
So instead, I want to write a Python notebook to showcase the following feature:

- If the keyboard suggests a word, like "amis" above, automatically decide if it's a name that should/could be written in an inclusive form,
- And for words that can have inclusive form, automatically compute it : "amis" → "ami-e-s".

Warning: there is so many exceptions, like "chevaux" is "cheval" at plurals, but feminine is "jument" so instead of "chevaux-ales" you write "chevaux/juments". Quite hard to be perfect in an automated way.

**Comment by Naereen** [comment]
Inspiration: https://github.com/norvig/pytudes/blob/master/ipynb/Gesture%20Typing.ipynb

**Comment by Naereen** [comment]
@GuilGautier @BastienTr @ThibaultGROUEIX : ça vous intéresse de m'aider éventuellement ? (ou genre de donner juste une relecture quand ce sera fini, pour suggérer des endroits où je pourrais améliorer des trucs)

**Comment by ThibaultGROUEIX** [comment]
Je te réponds en privé. A+ :)

**Comment by Naereen** [comment]
Le site [Lexique.org](http://www.lexique.org/) propose une énorme base de données qui contient *une partie* de ce qu'il faudra pour ce projet.

Par exemple pour trouver le pluriel de "cheval" :+1: [voir cette requête](http://www.lexique.org/moteur/complexe.php?regex=0&nom_champs%5B1%5D=lexique3.lemme&like%5B1%5D=&champs%5B1%5D=cheval&nom_champs%5B2%5D=lexique3.ortho&like%5B2%5D=&champs%5B2%5D=&nom_champs%5B3%5D=lexique3.ortho&like%5B3%5D=&champs%5B3%5D=&nom_champs%5B4%5D=lexique3.ortho&like%5B4%5D=&champs%5B4%5D=&tri=RAND%28%29&sens=ASC&pers%5B0%5D=*&pers%5B0%5D=Non_Sp%E9cifi%E9&pers%5B1%5D=Non_Sp%E9cifi%E9&pers%5B2%5D=Non_Sp%E9cifi%E9&pers%5B3%5D=Non_Sp%E9cifi%E9&pers%5B4%5D=Non_Sp%E9cifi%E9&pers%5B5%5D=Non_Sp%E9cifi%E9&database=lexique.lexique3&lienbdd=&Rechercher=Rechercher&nblignes=500&format=html).

ortho | phon | lemme
-- | -- | --
| chevaux | S°vo | cheval
| cheval | S°vo | cheval

**Comment by Naereen** [comment]
Fin septembre 2020 j'avais écrit ça, pour générer un dictionnaire de mots en écriture inclusive :
https://github.com/Naereen/notebooks/blob/master/Ecriture%20inclusive.ipynb
J'avais oublié ce ticket !

Ce vieux notebook n'avait pas implémenté grand chose :
https://github.com/Naereen/notebooks/blob/master/Algorithmes_pour_l_ecriture_inclusive.ipynb

Bon, j'abandonne, j'aurai jamais le temps et l'énergie de créer une appli mobile qui soit un bon clavier en écriture inclusive...
