### ISSUE TITLE
Runge-Kutta and numba

### ISSUE THREAD

**Issue by thomaslettau** [Naereen/notebooks#37]
I have a small comment regarding: Runge-Kutta_methods_for_ODE_integration_in_Python
I know, you uploaded the notebook 6 years ago, but I still think it is a nice little resource to play around with. If you change the decorator from @jit to @njit, numba is prevented from going into "python-mode" meaning it cannot fall back to simply not compiling the runge-kutta-method. In this way you can see that you need to also compile pend() and f() with numba because a numba compiled function can only take numba compiled functions as arguments:

```
Time of solving this ODE for 100 points with odeint method...
143 µs ± 16.4 µs per loop (mean ± std. dev. of 7 runs, 10,000 loops each)
Time of solving this ODE for 100 points with rungekutta4_jit method...
66.3 µs ± 2.38 µs per loop (mean ± std. dev. of 7 runs, 10,000 loops each)
```

If you would add this small comment, I would be really glad, if not, feel free to delete this issue.

**Comment by Naereen** [comment]
Hi there @TheIdealis,
Thanks for your interest in my (old) work!
I won't have time to add this remark, sorry. I don't have a laptop with numba installed right now.
Kind regards!
